spring.application.name=webshop-films-backend
server.port=26856

spring.datasource.url=jdbc:postgresql://localhost:5432/webshop_s1156856
spring.datasource.username=s1156856
spring.datasource.password=s1156856
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.max-lifetime=20000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=10000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=01234567890123456789012345678901
app.jwt.expiration-ms=86400000
