server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB:webshop-films-db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

app.jwt.secret=${JWT_SECRET:eenHeelLangEnWillekeurigGeheimVoorDockerOntwikkeling12345!}
app.jwt.expiration-ms=86400000
