server.port=26856

spring.datasource.url=jdbc:postgresql://localhost:5432/webshop-films-db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.max-lifetime=20000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=10000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt.secret=01234567890123456789012345678901
app.jwt.expiration-ms=86400000
