server.port=8081

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/webshop-films-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt.secret=eenHeelLangEnWillekeurigGeheimVoorMijnLokaleOntwikkeling12345!
# JWT expiration in milliseconds
app.jwt.expiration-ms=86400000
